### ISSUE TITLE
Needs to upgrade the dotnet framework

### ISSUE THREAD

**Issue by jonyeezs** [billpratt/dotnet-search#14]
The current dotnet framework that needs to be installed is version 2.0.

It does not support the latest TLS version.

And you get an error

> No usable version of the libssl was found

Should update this to the latest dotnetcore.app version so we don't have to worry of installing an older TLS version on our machine

**Comment by billpratt** [comment]
Apologizes for the long delay. This has been fixed with [version 1.0.1](https://www.nuget.org/packages/dotnet-search/1.0.1)
